export const END_POINTS = {
  BASE: 'api/v1',
  AUTH: {
    BASE: '/auth',
    SIGN_IN_BY_EMAIL: '/sign-in/email',
    SIGN_UP_BY_EMAIL: '/sign-up/email',
    SIGN_OUT: '/sign-out',
    REFRESH: '/refresh-token',
    RESET_PASSWORD: '/reset-password',
    CONFIRM_RESET_PASSWORD: '/confirm-reset-password',
    VERIFY_EMAIL_ACCOUNT: '/verify-email',
  },
  USERS: {
    BASE: '/users',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update',
    DISABLE: '/:id/disable',
    ENABLE: '/:id/enable',
    GET_ONE: '/get-one/:id',
    SEARCH: '/search',
  },
  FOODS: {
    BASE: '/foods',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update/:id',
    DISABLE: '/disable/:id',
    GET_ONE: '/get-one/:id',
    ENABLE: '/enable/:id',
    SEARCH: '/search',
  },
  CATEGORIES: {
    BASE: '/categories',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update/:id',
    DISABLE: '/disable/:id',
    GET_ONE: '/get-one/:id',
    ENABLE: '/enable/:id',
    SEARCH: '/search',
  },
  CARTS: {
    BASE: '/carts',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE_CART: '/update',
    GET_ONE: '/:id',
    ADD_TO_CART: '/add-to-cart',
    REMOVE_FROM_CART: '/remove-from-cart/:bookId',
    CHECKOUT_CART: '/checkout',
  },
  ORDER: {
    BASE: '/orders',
    GET_FULL_LIST: '/list',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE_STATUS: '/status/update/:id',
    GET_ONE: '/get-details/:id',
    CANCEL_ORDER: '/:id/cancel-order',
    GET_ONE_BY_ADMIN: '/get-details-by-admin/:id',
  },
  DASHBOARD: {
    BASE: '/dashboard',
    GET_BOOK_REPORT: '/get-book-report',
    GET_ORDER_REPORT: '/get-order-report',
    GET_ORDER_SHPPING_RATE: '/get-order-rate',
  },
  REVIEW: {
    BASE: '/reviews',
    GET_ALL: '/get-all',
    GET_ONE: '/:id',
    REPLY: '/:id/reply',
  },
  GOOGLE_OAUTH: {
    BASE: '/auth/google',
    REDIRECT: '/oauth2/redirect/code',
  },
};