export const END_POINTS = {
  BASE: 'api/v1',
  AUTH: {
    BASE: '/auth',
    SIGN_IN: {
      BASE_SIGN_IN: '/sign-in',
      EMAIL: '/email',
      PHONE: '/phone',
    },
    SIGN_UP: {
      BASE_SIGN_UP: '/sign-up',
      EMAIL: '/email',
      PHONE: '/phone',
    },
    SIGN_OUT: '/sign-out',
    REFRESH: '/refresh-token',
    GET_ME: '/get-me',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
  },
  USERS: {
    BASE: '/users',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update',
    DISABLE: '/:id/disable',
    ENABLE: '/:id/enable',
    GET_ONE: '/get-one/:id',
    UPDATE_BY_ADMIN: '/update-by-admin',
    SEARCH: '/search',
  },
  PRODUCTS: {
    BASE: '/products',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update/:id',
    GET_ONE: '/get-one/:id',
    SEARCH: '/search',
    FILTER: '/filter',
    SORT: '/sort',
    ACTIVE: '/active/:id',
    INACTIVE: '/inactive/:id',
    COMMENT: '/:id/comment',
    SEARCH_BY_PRICE: '/search/price',
    SEARCH_BY_RATING: '/search/rating',
    SEARCH_BY_CATEGORY: '/search/:categoryId',
  },
  AUTHORS: {
    BASE: '/authors',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update',
    GET_ONE: '/:id',
  },
  CATEGORIES: {
    BASE: '/categories',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update/:id',
    DISABLE: '/disable/:id',
    GET_ONE: '/get-one/:id',
    ENABLE: '/enable/:id',
    SEARCH: '/search',
  },
  CARTS: {
    BASE: '/carts',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE_CART: '/update',
    GET_ONE: '/:id',
    ADD_TO_CART: '/add-to-cart',
    REMOVE_FROM_CART: '/remove-from-cart/:bookId',
    CHECKOUT_CART: '/checkout',
  },
  CART_ITEM: {
    BASE: '/cart-items',
    GET_ALL: '/get-all',
    GET_DETAILS: '/get-details',
    CREATE: '/create',
    UPDATE: '/update',
    GET_ONE: '/:id',
  },
  ORDER: {
    BASE: '/orders',
    GET_FULL_LIST: '/list',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE_STATUS: '/status/update/:id',
    GET_ONE: '/get-details/:id',
    CANCEL_ORDER: '/:id/cancel-order',
    GET_ONE_BY_ADMIN: '/get-details-by-admin/:id',
    CREATE_ORDER_PAYMENT_URL_WITH_MOMO: '/create-order-payment-url-with-momo',
    CALLBACK_WITH_MOMO: '/momo/ipn-callback',
  },
  ORDER_DETAILS: {
    BASE: '/order-details',
    GET_ALL: '/get-all',
    CREATE: '/create',
    UPDATE: '/update',
    GET_ONE: '/:id',
  },
  DASHBOARD: {
    BASE: '/dashboard',
    GET_BOOK_REPORT: '/get-book-report',
    GET_ORDER_REPORT: '/get-order-report',
    GET_ORDER_SHPPING_RATE: '/get-order-rate',
  },
  REVIEW: {
    BASE: '/reviews',
    GET_ALL: '/get-all',
    GET_ONE: '/:id',
    REPLY: '/:id/reply',
    GET_REVIEW_BY_PRODUCT_ID: '/get-review-by-product-id/:productId',
    GET_REVIEW_BY_ORDER_ID: '/get-review-by-order-id/:orderId',
  },
  GOOGLE_OAUTH: {
    BASE: '/auth/google',
    REDIRECT: '/oauth2/redirect/code',
  },
  ADDRESS: {
    BASE: '/address',
    GET_ALL_BY_USER: '/get-all-by-user',
    GET_ALL_BY_ADMIN: '/get-all-by-admin',
    CREATE: '/create',
    UPDATE: '/update/:id',
    DELETE: '/delete/:id',
  },
};
